- jcl/install/VclGui/JediGUIMain.dfm
Correctly set the Anchors property on the "Install selected only"
checkbox so that it repositions as expected when the form is resized.
> Set Anchors on "Install selected only"

- jcl/source/windows/JclPeImage.pas
PeMapImgResolvePackageThunk  function raises access violation in 64bit application compiled with packages.
This is because Jmp instruction in 64bit code works differently than in 32bit code. 
Here is SO question with more details: 
http://stackoverflow.com/questions/7644508/how-to-interpret-jmp-dword-ptr-rel-00005e52
With this fix applied PeMapImgResolvePackageThunk  doesn't raise access violation  and returns correct address.
> Fixed incorrect address calculation in PeMapImgResolvePackageThunk function in 64bit mode

- jcl/source/windows/JclCIL.pas
Delphi 10.1 Berlin has a new property "Options" in TStrings, which gets in conflict with the current code (using `with TStringList.Create do` ...). Fixed by renaming the function's parameter from "Options" to "aOptions".
> compiles with D10.1 Berlin

- jcl/install/JclInstall.pas
During installation, if "Check HPP files" is checked and "HPP path" is set to point to a custom path (i.e. something different from BDS standard include path), compilation of jcl_a2z.cpp and jcl_z2a.cpp fails.
This is due to the custom path not being passed to the bcc compiler using the -I option.
> Added switches to BCC options to locate hpp files in custom directories

- jcl/source/common/JclPCRE.pas
PCRE_INFO_NAMETABLE: In the 16-bit library, the pointer points to 16-bit data units, the first of which contains the parenthesis number.
(http://www.pcre.org/original/doc/html/pcreapi.html)
> TJclWideRegEx.GetCaptureName must only add 1 to the PWideChar.

- jcl/source/windows/JclSvcCtrl.pas
Added functionality to JclSvcCtrl.pas' TJclNtService to be able to change an existing Windows Service's ServiceStartName and/or Password (i.e. its "Log On As" credentials).
> Updated TJclNtService to be able to change "Log On As" credentials

- jcl/source/vcl/JclVersionCtrlGITImpl.pas
Starting in git 2.5, the "git worktree" command was added which added support for multiple git worktrees attached to one existing git repository.  Yes I realize that "git worktree" is still experimental.
This pull request adds support for utilizing the Version Control menu for repositories that are additional worktrees.  Without this pull request, the various menus are disabled... ie. Blame, Commit, Log, ... are all grayed out.
One caveat to this pull request is that "git worktree" is not yet supported by tortoise git because it is not yet supported by [libgit2](https://github.com/libgit2/libgit2/pull/3436), however, there is a [pull request](https://gitlab.com/tortoisegit/tortoisegit/merge_requests/62) in place that has it fully functional in TortoiseGit.
> Add git multiple worktree and submodule support to the "Version Control" menu

- .gitmodules
Using a relative url allows for ssh cloning of the submodule and better mirroring on other servers.
> Use relative url in gitmodules

- jcl/source/windows/JclDebug.pas
Added ability to get line numbers by index and get unit name for corresponding line number. This is used in Delphi Code Coverage tool
> Added ability to get line numbers by index

- jcl/source/common/JclFileUtils.pas
Proposed fix for the ParamValue part of this one:
http://issuetracker.delphi-jedi.org/view.php?id=6621
> Fix for JclFileUtils ParamValue always performing case inseisitive search

- jcl/source/common/JclCompression.pas
Fix for this one: http://issuetracker.delphi-jedi.org/view.php?id=6647
> Archive.CurrentItemIndex may return 0 in DoProgress when Archive.ItemCount is zero in TJclCompressionArchive

- jcl/source/windows/JclPeImage.pas
Fix for the case where NameCount is 0 as reported in:
http://issuetracker.delphi-jedi.org/view.php?id=6660
> Fix for EIntOverflow in TJclPeExportFuncList.CreateList

- jcl/source/windows/Snmp.pas
Fix for this report:
http://issuetracker.delphi-jedi.org/view.php?id=6649
> Fix for wrongly declared parameter in SnmpUtilOidFree WinAPI import

- jcl/source/common/JclCompression.pas
Strangely there is a comment on the issue claiming that this value had been added in an earlier commit already. Here it is again.
http://issuetracker.delphi-jedi.org/view.php?id=5464
> TJclZipCompressArchive.GetSupportedCompressionMethods missing cmPPMd 

- jcl/source/common/JclContainerIntf.pas
Fixed the additional duplicate GUIID mentioned in:
http://issuetracker.delphi-jedi.org/view.php?id=6557
by assigning a new GUIID to IJclExtendedArray
> Fixed duplicate GUIID of IJclPtrArray and IJclExtendedArray

- jcl/source/common/JclContainerIntf.pas
Fixed http://issuetracker.delphi-jedi.org/view.php?id=6557 by assigning IJclAnsiStrAnsiStrMap a new GUIID
> Fixed duplicate GUIIDs of IJclAnsiStrIntfMap and IJclAnsiStrAnsiStrMap

- jcl/source/vcl/JclGraphUtils.pas
Replaced SizeOf with Length, which is one of the not disputed commits contained in this pull request: 
https://github.com/project-jedi/jcl/pull/44
I made a separate pull request out of this in order to get this non disputed part in Jcl.
> JclGraphUtils GDIError: replaced SizeOf by Length

- jcl/experts/debug/converter/JclDebugIdeImpl.pas
If the setting to display results is off, they should not be displayed.
> JclDebugIdeImpl: do not display results if turned off

- jcl/devtools/jpp/jpp.dof
- jcl/devtools/jpp/jppContainers.dof
- jcl/devtools/jpp/jppExceptionDialogs.dof
Fix the compiler search path to ensure the compiler uses the source code from the current source tree.
Currently the compiler search path for jpp, jppContainers and jppExceptionDialogs only specifies the include directory from the same source tree as '..\..\source\include'. This means that the source code files the compiler needs to compile these projects that are not in that include directory will, if available, be fetched from somewhere else; typically another JCL installation as specified by the registry.
This pull request add the common and windows source directory of the same source tree (..\..\source\common;..\..\source\windows) to the compiler search path.
> Fix the compiler search path of devtools (jpp, jppContainers and jppExceptionDialogs).

- jcl/source/common/JclSortedMaps.pas
- jcl/source/prototypes/containers/JclSortedMaps.imp
Fix a bug in the AssignDataTo method of the sorted map containers. The fix ensures the data is actually copied.
Currently the AssignDataTo method only 'copies' the reference to the internal storage array (FEntries). This means that after AssignDataTo is called both the source and target sorted map instance point to the same internal storage array (FEntries). And, after one of the instances is deleted the FEntries member of the other instance points to a memory buffer that has just been freed.
Which will lead to some rather annoying exceptions :-)
> Fix a memory bug in the AssignDataTo method of the sorted map containers.

- jcl/source/common/JclQueues.pas
- jcl/source/prototypes/containers/JclQueues.imp
- jcl/source/prototypes/containers/JclQueues.int
Currently the JclQueues containers do not implement overrides of the  AutoGrow, AutoPack and Grow methods. Effectively this means that the AutoGrow, AutoPack and Grow functionality does not work properly in the JclQueues classes. Please note that, by design, the JclQueues containers do not use the FSize field of the TJclAbstractContainerBase base class but determines the size dynamically when needed.
This pull request also fixes issue 6637 from the JEDI Issue Tracker (https://issuetracker.delphi-jedi.org/).
> JclQueues: Add missing AutoGrow, AutoPack and Grow methods.

- jcl/source/common/JclArrayLists.pas
- jcl/source/prototypes/JclArrayLists.pas
Ensure the array list (TJclArrayList<T>) iterator does not inadvertently free the parent array list if the parent array list is only referenced through an object reference instead of an interface reference.
> Fix memory corruption in the array list (TJclArrayList<T>) iterator.

- jcl/source/common/JclLinkedLists.pas
- jcl/source/prototypes/JclLinkedLists.pas
Ensure the linked list (TJclLinkedList<T>) iterator does not inadvertently free the parent linked list if the parent linked list is only referenced through an object reference instead of an interface reference.
> Fix memory corruption in the linked list (TJclLinkedList<T>) iterator.

- jcl/source/common/JclVectors.pas
- jcl/source/prototypes/JclVectors.pas
Ensure the vector (TJclVector<T>) iterator does not inadvertently free the parent vector if the parent vector is only referenced through an object reference instead of an interface reference.
> Fix memory corruption in the vector (TJclVector<T>) iterator.

- jcl/source/common/JclSortedMaps.pas
- jcl/source/prototypes/containers/JclSortedMaps.imp
Fix a bug in the MapEquals method of the sorted map containers to ensures both values and keys are actually compared.
The current code fails if two sorted maps are compared that have the AllowDefaultElements and ReturnDefaultElements properties set, contain the same number of elements and contain key value pairs for which the key differs and the value is the same as the 'default value' (nil, '', etc...).
For example: a TJclStrStrSortedMap map1 containing key1='' and a TJclStrStrSortedMap map2 containing key2='' will be considered equal by the current implementation of MapEquals.
This is due to the fact that map2.GetValue('key1') will return the default value ''.
The MapEquals code line that causes the problem is:
if ValuesCompare(AMap.GetValue(AKey), FEntries[Index].Value) <> 0 then
> Fix a bug in the MapEquals method of the sorted map containers.

- jcl/source/prototypes/JclBinaryTrees.pas
Ensure the binary tree iterator does not inadvertently free the parent binary tree if the parent binary tree is only referenced through an object reference instead of an interface reference.
This update should have been part of pull request #68.
> Fix memory corruption in the binary tree iterators. (follow up to pull request #68)

- qa/automated/dunit/units/TestJclMath.pas
The implemented but then commented tests hint at some discrepancy between JclMath and System.Math.
> Implemented some of the empty math unit tests

- qa/automated/dunit/units/TestJclDebug.pas
Changed checks to match what's returned as including the file suffix for a file name seems resonable for me.
> Unit tests jcl debug

- jcl/source/windows/JclPeImage.pas
When Delphi places debug info into the executable, it sets the debug image directory size to the count of the number of entries, not the total size of all of the entries. This contrasts with MSVC (presumably the standard) which places the size into the executable. In order to be compatible as much as possible, this fix checks for TD32 debug info and uses count if TD32 debug info is present, otherwise using total size divided by header size.
Also, debug information can be in *any* section, so only checking `.debug` or `.rdata` isn't appropriate. Just use the header to determine where in the executable to look by using the `RvaToVa()` method.
> Fixing debug directory virtual address calculation

- jcl/source/windows/JclDebug.pas
In case a Unit contains an uppercase character after the first dot (e.g. DUnitX.Test**R**unner), the "FixedProcedureName" inside GetLocationInfoStr is malformed.
TJclLocationInfo.UnitName: 'DUnitX.TestRunner'
TJclLocationInfo.ProcedureName: 'Testrunner.TDUnitXTestRunner.ExecuteTest'
Tries to remove 'TestRunner' from TJclLocationInfo.ProcedureName which results into 'Testrunner.TDUnitXTestRunner.ExecuteTest'
Current Behavior
`(000A12BB){Xyz.exe} [004A22BB] DUnitX.TestRunner.Testrunner.TDUnitXTestRunner.ExecuteTest (Line 740, "DUnitX.TestRunner.pas" + 11) + $8`
Expected Behavior
`(000A12BB){Xyz.exe} [004A22BB] DUnitX.TestRunner.TDUnitXTestRunner.ExecuteTest (Line 740, "DUnitX.TestRunner.pas" + 11) + $8`
> Malformed FixedProcedureName inside Callstack

- jcl/source/common/JclBase.pas
This line caused random compile errors, expecting ; but got . 
Removing the reference to JclBase seems to solve the error below:
```
Jedi-jcl\source\common\JclBase.pas(116Error: E2029 ';' expected but '.' found
Jedi-jcl\source\common\JclBase.pas(310Fatal: F2063 Could not compile used unit 'JclResources.pas'
```
i've only gotten this error when removing my DCU'S.
> Fix random compile error

- jcl/source/common/JclCompilerUtils.pas
- jcl/source/common/JclIDEUtils.pas
Hi, please accept this pull request.
What is implemented:
+ Added constants for platforms that are supported on newer Delphi versions.
+ Added command line tools for added platforms (classes, types and constants).
We use this in our project open source project for inspecting installed Delphi versions and platforms.
> Added supported platforms for newer Delphi versions

- jcl/source/common/JclResources.pas
- jcl/source/common/JclSysInfo.pas
Added Windows 11 version detection for `GetWindowsVersion` and the public variable `IsWin11`.
Kept the Windows 10 based 'editions' and `GetWindows10...` functions as Windows 11 basically is still a 'Windows 10' version:
- see newly introduced `GetWindowsProductName` method
> Added Windows 11 version detection

- jcl/source/common/JclSysInfo.pas
Added generic function 'GetWindowsReleaseCode' to get the release 'Code' of a Windows version (starting Win10).
> Extend Windows version in with retine to get ReleaseCode

- jcl/source/common/JclResources.pas
- jcl/source/common/JclSysInfo.pas
- jcl/source/windows/JclSvcCtrl.pas
https://issuetracker.delphi-jedi.org/view.php?id=6701
TJclSCManager system error 87 (parameter incorrect) in Delphi 10.4 running on older Windows version (Windows 7, Windows 2008 server.. )
https://issuetracker.delphi-jedi.org/view.php?id=6734
Windows 2022 Server detection missing
https://issuetracker.delphi-jedi.org/view.php?id=6745
Range check error calling OpenSCManager on win64 using Alexandria 11.1
> Resolved issues 6701, 6734, 6745

- jcl/source/common/JclWideStrings.pas
StrScanW has a bug: Dec(StrLen) missing
> fixed StrScanW: need Dec(StrLen)

- jcl/source/common/JclSysInfo.pas
PID must be DWORD, not THandle (error occurs when build for 64 bit)
> Fixed error for Win64 target

- jcl/source/common/JclSysInfo.pas
Bios date location in registry seems to have changed at least since W10
> Bios date location changed in W10

- jcl/source/common/JclSimpleXml.pas
I ran across a case where `TJclSimpleXMLElems.Sort` had to be called twice in order to get the correct/expected ordering.
The internal `JclSimpleXml.QuickSort` implementation has a bug in its pivot selection/management.
* The sort assumes that the pivot index (`M`) never changes.
* When elements are exchanged, the pivot may be one of the impacted elements. In this the case, `M` should be updated.
This surfaces as incorrect sorting in `TJclSimpleXMLElems.Sort` and `TJclSimpleXMLElems.CustomSort`.
> Fix pivot selection in `JclSimpleXml.QuickSort`

- jcl/experts/common/JclOtaResources.pas
- jcl/experts/common/JclOtaUtils.pas
- jcl/experts/debug/converter/JclDebugIdeImpl.pas
When using [Better Translation Manager](https://bitbucket.org/anders_melander/better-translation-manager), PE executables with translations will be created next to target exe file. Depending on their language and extension they may be found faster than exe itself by function FindExecutableName. Usage of this function is unreliable and not required since we have target executable name available in project settings in Delphi 8 and newer. Delphi 7 will have old logic, but it will be easier to find problem because of better logging.
> Take target file name from project settings instead of guessing

- jcl/source/common/JclLogic.pas
mixed up places for registers A[HL] and C[HL]
> Fix asm x64 implemetation for ReverseBytes functions with two-byte arguments

- jcl/source/common/JclResources.pas
- jcl/source/common/JclSysInfo.pas
Since an analysis of the Windows Registry revealed that the WindowReleaseId of Windows Server 2025 is identical to that of Windows Server 2022 (namely 2009), I conducted a check on the WindowsBuildNumber, which should be greater than or equal to 26100 for Server 2025 (https://learn.microsoft.com/en-us/windows-server/get-started/windows-server-release-info).
> Windows Server 2025 detection
